name: CI
on:
  [push, pull_request]
jobs:
  Awesome_Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run linter 👀
        run: npx awesome-lint
